import 'package:sunglasses_show/model/movie.dart';
import 'package:sunglasses_show/model/tv_show.dart';

List<Movie> getMovies() => <Movie>[
      Movie(
          "A Star Is Born",
          "assets/images/movies/poster_overlord.jpg",
          2017,
          "Drama, Romance, Music",
          "2h 16m",
          "R",
          7.2,
          "October 3, 2018",
          "US",
          "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
          "Bradley Cooper"),
      Movie(
          "Alita: Battle Angel",
          "assets/images/movies/poster_alita.jpg",
          2019,
          "Action, Science Fiction, Adventure",
          "2h 2m",
          "PG-13",
          7.7,
          "January 31, 2019",
          "US",
          "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
          "Robert Rodriguez"),
      Movie(
          "Aquaman",
          "assets/images/movies/poster_aquaman.jpg",
          2018,
          "Action, Adventure, Fantasy",
          "2h 23m",
          "PG-13",
          6.9,
          "December 7, 2018",
          "US",
          "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.",
          "James Wan"),
      Movie(
          "Bohemian Rhapsody",
          "assets/images/movies/poster_bohemian.jpg",
          2018,
          "Music, Drama, History",
          "2h 23m",
          "PG-13",
          8.0,
          "October 24, 2018",
          "US",
          "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
          "Bryan Singer"),
      Movie(
          "Cold Pursuit",
          "assets/images/movies/poster_cold_pursuit.jpg",
          2019,
          "Action, Crime, Thriller",
          "1h 59m",
          "PG-13",
          5.7,
          "February 7, 2019",
          "US",
          "The quiet family life of Nels Coxman, a snowplow driver, is upended after his son's murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking's associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution.",
          "Hans Petter Moland"),
      Movie(
          "Creed II",
          "assets/images/movies/poster_creed.jpg",
          2018,
          "Drama",
          "2h 10m",
          "PG-13",
          6.9,
          "November 21, 2018",
          "US",
          "Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.",
          "Steven Caple Jr."),
      Movie(
          "Fantastic Beast: The Crime of Grindelwald",
          "assets/images/movies/poster_crimes.jpg",
          2018,
          "Adventure, Fantasy, Drama",
          "2h 14m",
          "PG-13",
          6.9,
          "November 14, 2018",
          "US",
          "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
          "David Yates"),
      Movie(
          "Glass",
          "assets/images/movies/poster_glass.jpg",
          2019,
          "Thriller, Drama, Science Fiction",
          "2h 9m",
          "PG-13",
          6.7,
          "January 16, 2019",
          "US",
          "In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.",
          "M. Night Shyamalan"),
      Movie(
          "How to Train Your Dragon",
          "assets/images/movies/poster_how_to_train.jpg",
          2010,
          "Fantasy, Adventure, Animation, Family",
          "1h 38m",
          "PG",
          7.8,
          "March 10, 2010",
          "US",
          "As the son of a Viking leader on the cusp of manhood, shy Hiccup Horrendous Haddock III faces a rite of passage: he must kill a dragon to prove his warrior mettle. But after downing a feared dragon, he realizes that he no longer wants to destroy it, and instead befriends the beast – which he names Toothless – much to the chagrin of his warrior father.",
          "Dean DeBlois"),
      Movie(
          "Avengers: Infinity War",
          "assets/images/movies/poster_infinity_war.jpg",
          2018,
          "Adventure, Action, Science Fiction",
          "2h 29m",
          "PG",
          8.3,
          "April 25, 2018",
          "US",
          "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
          "Joe Russo"),
      Movie(
          "Master Z: Ip Man Legacy",
          "assets/images/movies/poster_master_z.jpg",
          2018,
          "Action",
          "1h 47m",
          "PG-13",
          5.9,
          "December 20, 2018",
          "US",
          "Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it's not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.",
          "Yuen Woo-ping"),
      Movie(
          "Mortal Engines",
          "assets/images/movies/poster_mortal_engines.jpg",
          2018,
          "Adventure, Science Fiction",
          "2h 9m",
          "PG-13",
          6.1,
          "November 27, 2018",
          "US",
          "Many thousands of years in the future, Earth’s cities roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive traction cities, the old London, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the wastelands who will change the course of his life forever.",
          "Christian Rivers"),
      Movie(
          "Overlord",
          "assets/images/movies/poster_overlord.jpg",
          2018,
          "Horror, War, Science Fiction",
          "1h 50m",
          "R",
          6.1,
          "November 1, 2018",
          "US",
          "France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.",
          "Julius Avery"),
      Movie(
          "Ralph Breaks the Internet",
          "assets/images/movies/poster_ralph.jpg",
          2018,
          "Family, Animation, Comedy, Adventure",
          "1h 52m",
          "PG",
          7.2,
          "November 20, 2018",
          "US",
          "Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, Sugar Rush. In way over their heads, Ralph and Vanellope rely on the citizens of the internet — the netizens — to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.",
          "Phil Johnston"),
      Movie(
          "Robin Hood",
          "assets/images/movies/poster_robin_hood.jpg",
          2018,
          "Adventure, Action, Thriller",
          "1h 56m",
          "PG-13",
          5.9,
          "November 21, 2018",
          "US",
          "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
          "Otto Bathurst"),
      Movie(
          "Spider-Man: Into the Spider-Verse",
          "assets/images/movies/poster_spiderman.jpg",
          2018,
          "Action, Adventure, Animation, Science Fiction, Comedy",
          "1h 57m",
          "PG",
          8.4,
          "December 6, 2018",
          "US",
          "Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson 'Kingpin' Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.",
          "Rodney Rothman"),
      Movie(
          "T-34",
          "assets/images/movies/poster_t34.jpg",
          2018,
          "War, Action, Drama, History",
          "2h 19m",
          "PG",
          6.4,
          "December 27, 2018",
          "RU",
          "In 1944, a courageous group of Russian soldiers managed to escape from German captivity in a half-destroyed legendary T-34 tank. Those were the times of unforgettable bravery, fierce fighting, unbreakable love, and legendary miracles.",
          "Alexey Sidorov"),
    ];

List<TVShow> getTVShows() => <TVShow>[
      TVShow(
          "Arrow",
          "assets/images/tv_shows/poster_arrow.jpg",
          2012,
          "Crime, Drama, Mystery, Action & Adventure",
          "42m",
          "TV-14",
          6.6,
          "October 10, 2012",
          "US",
          "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
          "Greg Berlanti"),
      TVShow(
          "Doom Patrol",
          "assets/images/tv_shows/poster_doom_patrol.jpg",
          2019,
          "Sci-Fi & Fantasy, Comedy, Drama",
          "49m",
          "TV-MA",
          7.6,
          "February 15, 2019",
          "US",
          "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.",
          "Jeremy Carver"),
      TVShow(
          "Dragon Ball Z",
          "assets/images/tv_shows/poster_dragon_ball.jpg",
          1989,
          "Animation, Sci-Fi & Fantasy, Action & Adventure",
          "26m",
          "TV-PG",
          8.2,
          "April 26, 1989",
          "US",
          "Five years have passed since the fight with Piccolo Jr., and Goku now has a son, Gohan. The peace is interrupted when an alien named Raditz arrives on Earth in a spacecraft and tracks down Goku, revealing to him that that they are members of a near-extinct warrior race called the Saiyans.",
          "Akira Toriyama"),
      TVShow(
          "Fairy Tail: Phoenix Priestess",
          "assets/images/tv_shows/poster_fairytail.jpg",
          2012,
          "Action, Adventure, Comedy, Fantasy, Animation",
          "1h 26m",
          "PG-13",
          7.3,
          "August 18, 2012",
          "US",
          "The film revolves around a mysterious girl named Éclair who appears before Fairy Tail, the world's most notorious wizard's guild. She lost all of her memories, except for the imperative that she must deliver two Phoenix Stones somewhere. The stones may spell the collapse of the magical world, and Natsu, Lucy, and the rest of the Fairy Tail guild are caught up in the intrigue.",
          "Masaya Fujimori"),
      TVShow(
          "Family Guy",
          "assets/images/tv_shows/poster_family_guy.jpg",
          1999,
          "Animation, Comedy",
          "22m",
          "TV-14",
          7.0,
          "January 31, 1999",
          "US",
          "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
          "Seth MacFarlane"),
      TVShow(
          "The Flash",
          "assets/images/tv_shows/poster_flash.jpg",
          2014,
          "Drama, Sci-Fi & Fantasy",
          "22m",
          "TV-14",
          7.7,
          "October 7, 2014",
          "US",
          "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only 'meta-human' who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.",
          "Greg Berlanti"),
      TVShow(
          "Gotham",
          "assets/images/tv_shows/poster_gotham.jpg",
          2014,
          "Drama, Crime, Sci-Fi & Fantasy",
          "43m",
          "TV-14",
          7.5,
          "September 22, 2014",
          "US",
          "Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?",
          "Bruno Heller"),
      TVShow(
          "Grey's Anatomy",
          "assets/images/tv_shows/poster_grey_anatomy.jpg",
          2005,
          "Drama",
          "43m",
          "TV-14",
          8.2,
          "March 27, 2005",
          "US",
          "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
          "Shonda Rhimes"),
      TVShow(
          "Hanna",
          "assets/images/tv_shows/poster_hanna.jpg",
          2019,
          "Action & Adventure, Drama",
          "50m",
          "TV-14",
          7.5,
          "March 28, 2019",
          "US",
          "This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.",
          "David Farr"),
      TVShow(
          "Marvel's Iron Fist",
          "assets/images/tv_shows/poster_iron_fist.jpg",
          2017,
          "Action & Adventure, Drama, Sci-Fi & Fantasy",
          "55m",
          "TV-MA",
          6.6,
          "March 17, 2017",
          "US",
          "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny.",
          "Scott Buck"),
      TVShow(
          "Naruto Shippūden",
          "assets/images/tv_shows/poster_naruto_shipudden.jpg",
          2007,
          "Animation, Action & Adventure, Sci-Fi & Fantasy",
          "25m",
          "TV-14",
          8.6,
          "February 15, 2007",
          "US",
          "Naruto Shippuuden is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as He has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.",
          "Masashi Kishimoto"),
      TVShow(
          "NCIS",
          "assets/images/tv_shows/poster_ncis.jpg",
          2003,
          "Crime, Action & Adventure, Drama",
          "45m",
          "TV-14",
          7.4,
          "September 23, 2003",
          "US",
          "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.",
          "Donald P. Bellisario"),
      TVShow(
          "Riverdale",
          "assets/images/tv_shows/poster_riverdale.jpg",
          2017,
          "Mystery, Drama, Crime",
          "45m",
          "TV-14",
          8.6,
          "January 26, 2017",
          "US",
          "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
          "Roberto Aguirre-Sacasa"),
      TVShow(
          "Shameless",
          "assets/images/tv_shows/poster_shameless.jpg",
          2011,
          "Drama, Comedy",
          "57m",
          "TV-MA",
          8.6,
          "January 9, 2011",
          "US",
          "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.",
          "John Wells"),
      TVShow(
          "Supergirl",
          "assets/images/tv_shows/poster_supergirl.jpg",
          2015,
          "Drama, Sci-Fi & Fantasy, Action & Adventure",
          "42m",
          "TV-MA",
          7.2,
          "October 26, 2015",
          "US",
          "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
          "Greg Berlanti"),
      TVShow(
          "Supernatural",
          "assets/images/tv_shows/poster_supernatural.jpg",
          2015,
          "Drama, Mystery, Sci-Fi & Fantasy",
          "45m",
          "TV-14",
          8.2,
          "September 13, 2005",
          "US",
          "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way.",
          "Eric Kripke"),
      TVShow(
          "The Simpsons",
          "assets/images/tv_shows/poster_the_simpson.jpg",
          2015,
          "Family, Animation, Comedy",
          "22m",
          "TV-PG",
          7.8,
          "December 17, 1989",
          "US",
          "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
          "Matt Groening"),
      TVShow(
          "The Umbrella Academy",
          "assets/images/tv_shows/poster_the_umbrella.jpg",
          2019,
          "Action & Adventure, Sci-Fi & Fantasy, Drama",
          "55m",
          "TV-MA",
          8.7,
          "February 15, 2019",
          "US",
          "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
          "Steve Blackman"),
      TVShow(
          "The Walking Dead",
          "assets/images/tv_shows/poster_the_walking_dead.jpg",
          2019,
          "Action & Adventure, Drama, Sci-Fi & Fantasy",
          "42m",
          "TV-MA",
          8.1,
          "October 31, 2010",
          "US",
          "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
          "Frank Darabont"),
    ];
